### PR TITLE
Add support for nested JSON

### PR DESCRIPTION
**Pull request by tetraoxygen**
This PR adds support for encoding nested JSON. For example, you can encode a Codable datatype that includes other Codable types.

You can use this with Codable's polymorphism support to add small bits of data that support polymorphism by having a type annotation outside a nested object you intend to decode.

### CODE REVIEW

**Review by 0xTim — COMMENTED** [review]
@fabianfett any thoughts?

@tetraoxygen thanks for this! We'll need tests for the new behaviour at the very least

**Comment by tetraoxygen** [comment]
I've added tests for nested encoding, which is all I materially changed. I'm also happy to go write nested decode tests (though those just use Swift's standard `JSONDecoder`) if it would be useful.

**Comment by tetraoxygen** [comment]
@0xTim Following up on this — should I write more tests or do the ones I've added do the job?

**Comment by tetraoxygen** [comment]
I believe #207 would be solved by this PR (without the PostgresJSONCodable workaround)

**Review by 0xTim — CHANGES_REQUESTED** [review]
Could you set the spacing to 4 spaces instead of a tab to keep it consistent with the rest of the codebase?

@gwynne @fabianfett any comments?

**Comment by tetraoxygen** [comment]
Indentation should be fixed now

**Comment by sidepelican** [comment]
I have also this trouble. Thanks for the nice PR.

**Comment by gwynne** [comment]
This should be fixed with the new logic in #241

**Pull request closed without merging**
